### ISSUE TITLE
The official tomcat docker image comes with LANG set to C.UTF-8 which is not supported by Ellucian for Banner applications

### ISSUE THREAD

**Issue by gillfimj** [sig-docker/tomcat#24]
It has been observed in certain situations, like with the Student Self-Service application, the landing page contents will not display if a browser language is chosen that is not listed in GURINFO. The default functionality is supposed to be that if a chosen language does not exist, it should display the landing page define for the default locale set by the environment variable LC_ALL. By design LC_ALL overrides the value of the environment variable LANG. The current value of LC_ALL in the tomcat docker container is null and the delivered value of LANG by the makers of the official tomcat image is C.UTF-8. While this can be temporarily resolved by adding the LANG environment variable to sceptre yaml file to redefine what is delivered, ideally, the tomcat build should be modified to adhere to Ellucian recommended requirements. To do this, I believe the following could be done:

Add locales to the list of installed packages:
&& apt-get install -y locales \

Then add a section to add default locale support for en_US.UTF-8, something like this:

RUN touch /usr/share/locale/locale.alias
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

Further accommodations could be made to support other locales should we need to support other languages.

**Comment by dboitnot** [comment]
Since this is a banner-specific issue I've moved it to the banner-app image repo [here](https://github.com/sig-docker/banner-app/issues/2).
