### ISSUE TITLE
Alternate way to set timezone

### ISSUE THREAD

**Issue by gillfimj** [sig-docker/tomcat#25]
The tomcat container runs in UTC by default. The tomcat-ansible attempts to set the timezone by using timedatectl. The timedatectl utility doesn't exist in the Docker tomcat image and appears to only be installed with systemd which seems to carry a lot of overhead. A possible low cost option would be to use the /usr/share/zoneinfo to relink the localtime. It would look something like this:

ln -sf /usr/share/zoneinfo/US/Central /etc/localtime
or
ln -sf /usr/share/zoneinfo/America/Chicago /etc/localtime

Why is this important? Tracking dates of files, log entries and comparing them against the database gets a bit confusing when everything is not in the same timezone. While tomcat can set a JAVA_OPT, that value can be different than the OS timezone which is then different from the database.

**Comment by dboitnot** [comment]
We also need to address the hard-coding of:

https://github.com/sig-docker/tomcat/blob/0a6630b446d6e45e98bbc2c1ec878f731bc884f0/ansible/group_vars/all/tomcat.yml#L4

**Comment by dboitnot** [comment]
Available as of build 658.
