### ISSUE TITLE
Make less command available in tomcat container

### ISSUE THREAD

**Issue by gillfimj** [sig-docker/tomcat#40]
The **less** command has become more useful in reviewing lengthy logfiles than things like vi or more. Consider adding less to the package installation list to help in day-to-day troubleshooting of container contents.

**Comment by dboitnot** [comment]
I'm not _vehemently_ opposed to this, but I do try to minimize the image size so I tend to avoid adding utilities to service-type images like this one. My typical approach when troubleshooting is to install tools like less and/or vim while `exec`'d into the running container using apt.

As to logs specifically, ideally they'll be shipped to another service like CloudWatch for review. If you have logs which aren't being piped to STDOUT, that can be fixed using xtail. The default image fires up xtail just before launching Tomcat to monitor `$APP_LOGS` (`/app_logs`).

Will this work for your case?

**Comment by gillfimj** [comment]
So far, what I've been doing is modifying the Dockerfile for the banner app build to add the necessary pieces for troubleshooting. However, if the tomcat image is hardened and started as tomcat instead of root prior to building the banner app, like as a separate step (and not all at once as it might be done), then adding additional packages just won't be an option. However, in the case where the entire image is built at once, the only other place to add additional packages when starting the container as Tomcat, is in the Docker file for the banner app, like I'm currently doing. I know we're trying to stay as close to the official image as possible, so maybe this needs to be added elsewhere then. With a hardened tomcat image, you're pretty limited post container build and what worked in the past won't necessary work.

**Comment by dboitnot** [comment]
The `less` package is available in the baseline build (and all others) as of build 599.
